### ISSUE TITLE
getVolumeRange fails, maybe on negative values?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pyminc#16]
```python
from pyminc.volumes.factory import *
infile = volumeFromFile("/data/chamal/data/ABIDE/minc/ABIDE_CALTECH-51456.mnc")
infile.getVolumeRange()
---------------------------------------------------------------------------
mincException                             Traceback (most recent call last)
<ipython-input-5-27fbf8724ff1> in <module>()
----> 1 infile.getVolumeRange()

/opt/quarantine/pyminc/0.41/build/lib/python2.7/site-packages/pyminc-0.41-py2.7.egg/pyminc/volumes/volumes.pyc in getVolumeRange(self)
    243         status = libminc.miget_volume_range(self.volPointer, \
    244                                     byref(volume_max), byref(volume_min))
--> 245         testMincReturn(status)
    246         return (volume_max.value, volume_min.value)
    247 

/opt/quarantine/pyminc/0.41/build/lib/python2.7/site-packages/pyminc-0.41-py2.7.egg/pyminc/volumes/volumes.pyc in testMincReturn(value)
     12 def testMincReturn(value):
     13     if value < 0:
---> 14         raise mincException
     15 
     16 class mincVolume(object):
```

```shell
> mincstats /data/chamal/data/ABIDE/minc/ABIDE_CALTECH-51456.mnc
File:              /data/chamal/data/ABIDE/minc/ABIDE_CALTECH-51456.mnc
Mask file:         (null)
Total voxels:      6707360
# voxels:          6707360
% of total:        100
Volume (mm3):      6707360
Min:               -3
Max:               1033
Sum:               1022068783
Sum^2:             3.697102004e+11
Mean:              152.3801888
Variance:          31900.35994
Stddev:            178.6067186
CoM_voxel(z,y,x):  88.56719355 90.06019885 88.07274776
CoM_real(x,y,z):   0.7831863848 34.24663073 10.87227777

Histogram:         (null)
Total voxels:      6707360
# voxels:          6707360
% of total:        100
Median:            29.37500534
Majority:          -0.151
BiModalT:          208.085
PctT [  0%]:       -2.741
Entropy :          7.424872354
```

**Comment by jasonlerch** [comment]
negative values provide no problems to pyminc (just tested it myself).

Any chance this is a minc v1 volume? pyminc can only deal with minc v2. 

If that isn’t it, can you post the file somewhere so that we can help debug?

**Comment by gdevenyi** [comment]
MINC2 file, I can interact with the file in other ways, it's the getVolumeRange() that seems to cause issues.

https://www.dropbox.com/s/9z17anghgvunsnj/ABIDE_CALTECH-51456.mnc?dl=0

**Comment by jasonlerch** [comment]
Confirmed; but getVolumeRange fails on every file I’ve tried, so the bug doesn’t appear file dependent.

Incidentally, you should be able to work with the file otherwise unless you need an explicit getVolumeRange call. 

f2 = volumeFromFile("/micehome/jlerch/Dropbox/ABIDE_CALTECH-51456.mnc")
float(np.sum(f2.data))
Out[23]: 1022068928.0

If you just want the range of the data can you get away with using np.min and np.max? 

We’ll look into the getVolumeRange bug.

**Comment by gdevenyi** [comment]
Yup, I can do it other ways, just thought I'd report it, since I had trouble.

**Comment by mcvaneede** [comment]
Turns out that miget_volume_range() which we call in getVolumeRange only works when slice scaling is not enabled. That will rarely be the case... I'll add a test to see whether the slice scaling flag is enabled and return numpy's min() and max() on the data array otherwise.
