### ISSUE TITLE
update the libminc version check

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/pyminc#19]
Currently fix to miset_attr_values() (https://github.com/BIC-MNI/libminc/commit/3ca34259f7d5bdae11bf77226492457cb7a1922a) has not made it to a main release of libminc. When it does, we can check for the correct libminc version in writeFile() and use the correct function based on that. Right now, it will simply always choose to use the private miset_attribute() function.

**Comment by bcdarwin** [comment]
Fixed in b0ba16b2bd71dcfdcbaa8ecdcf3b18002a23f5fa.
