### ISSUE TITLE
Direction cosines not supported ?

### ISSUE THREAD

**Issue by cpresseau** [Mouse-Imaging-Centre/pyminc#22]
Hi,

is there a way to set direction cosines using a transform ? I can't find any way to do that. I would like to set the direction cosines using a numpy 3D array into volumeFromDescription. 

My use case is this : load a 4D MINC file, do some processing and get a 3D MINC file to save. I would like to keep the dimnames, starts, sizes, steps, direction_cosines, etc. from the 4D input file (the last 3 dimensions for all) and just change the the data.

I was currently using volumeFromDescription to do that, but there is no way to set the direction cosines. volumeFromFile doesn't work either because the openFile method doesn't copy the direction cosines. 

Does anybody knows a way to do that ? I need to save the same direction cosines as the input volume so my output and input are aligned properly. Any help would be appreciated. Thanks.

**Comment by mcvaneede** [comment]
Hi,

In terms of your use case, pyminc should already allow you to load a 4D MINC file, reduce it to a 3D MINC file and retain the header information you want:

```
in_4D = volumeFromFile("4D.mnc")
out_3D = volumeFromFromInstance(in_4D, "some_output_3D.mnc", dims=["xspace", "yspace", "zspace"])
in_4D.closeVolume()
# some fake work on the 3D file...
out_3D.data[::] = 10
out_3D.writeFile()
out_3D.closeVolume()
```

I'll add the ability to specify direction cosines for volumeFromDescription, but potentially this already provides you with a way to deal with your problem?

**Comment by mcvaneede** [comment]
Hi Caroline,

Another follow-up. The latest version of the develop pipeline allows you to use volumeFromDescription and volumeFromData and specify the direction cosines you want (https://github.com/Mouse-Imaging-Centre/pyminc/tree/41ef97afb56127cd0f27dccf8b134047938a47d6). I've made a couple more changes and will release a new version of pyminc soon.

To come back to the first question, currently you can not apply transformations to MINC instances in pyminc. It's on the list of features to be implemented, but I don't think that will happen very soon. Let me know if the above fixes don't solve your problem.
