### ISSUE TITLE
Cannot find libminc2.so

### ISSUE THREAD

**Issue by yohanyee** [Mouse-Imaging-Centre/pyminc#26]
If libminc2.so is already installed on the system and when installing pyminc via pip in Anaconda, the installation completes with no errors but importing pyminc results in an error related to finding libminc2.so . The issue is with the path to the library, which I fixed by symlinking ${ANACONDA_INSTALL_PATH}/lib/libminc2.so to /usr/lib/x86_64-linux-gnu/libminc2.so.4.0.0 . Can this step be added in the install process?

**Comment by gdevenyi** [comment]
Sounds like an issue with LD_LIBRARY_PATH

**Comment by bcdarwin** [comment]
I don't exactly understand what has gone wrong with your installation but I'm reluctant to add such ad hoc steps to the installation process.

________________________________

**Comment by MaximeDdnn** [comment]
I had the same issus. This step works for me : export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/minc/1.9.17/lib  (if you use minctoolkit v2)

**Comment by gdevenyi** [comment]
You have not run the "source" command specified for use of the minc-toolkit after install
